<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Plugin.Maui.Microchart.Core</PackageId>
    <Description>Core components for Plugin.Maui.Microchart.</Description>
    <TargetFrameworks>net10.0;net10.0-ios;net10.0-maccatalyst;net10.0-android</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageTags>maui;chart;charts;graphics;dotnet-maui</PackageTags>
    <UseMaui>true</UseMaui>
    <SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
