name: Plugin.Maui.Microchart PR Build
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Build for PR"
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-26]
    steps:
      - name: Clone source
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            10.0.x

      - name: "Install .NET workloads"
        run: |
          dotnet workload install android
          dotnet workload install ios
          dotnet workload install maccatalyst
          dotnet workload install maui
          dotnet workload list

      - name: Select Xcode
        if: matrix.os == 'macos-26'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: "Build solution"
        run: dotnet build Plugin.Maui.Microchart.slnx --configuration Release

      - name: "Pack Plugin.Maui.Microchart Core"
        run: dotnet pack src/Plugin.Maui.Microchart.Core/Plugin.Maui.Microchart.Core.csproj --configuration Release --no-build

      - name: "Pack Plugin.Maui.Microchart Droid"
        run: dotnet pack src/Plugin.Maui.Microchart.Droid/Plugin.Maui.Microchart.Droid.csproj --configuration Release --no-build

      - name: "Pack Plugin.Maui.Microchart iOS"
        run: dotnet pack src/Plugin.Maui.Microchart.iOS/Plugin.Maui.Microchart.iOS.csproj --configuration Release --no-build

      - name: "Pack Plugin.Maui.Microchart MAUI"
        run: dotnet pack src/Plugin.Maui.Microchart/Plugin.Maui.Microchart.csproj --configuration Release --no-build

      - name: "Pack Plugin.Maui.Microchart Meta-package"
        run: dotnet pack src/Plugin.Maui.Microchart.Metapackage/Plugin.Maui.Microchart.Metapackage.csproj --configuration Release
